### ISSUE TITLE
How do you use glob files

### ISSUE THREAD

**Issue by mrandrewandrade** [MLWave/Kaggle-Ensemble-Guide#1]
for the first argument, how do you use glob files?

**Comment by MLWave** [comment]
Hi, these work pretty much like `dir` on Windows and `ls` on Linux.

```
kaggle_avg.py mysubs\*.csv averaged_outputfile.csv
```

A note: Use these scripts for a quick run. You probably want to rewrite properly for more serious usage. Sorry for the poor documentation.

**Comment by mrandrewandrade** [comment]
Thanks!
