### ISSUE TITLE
Add weightage parameters for more customized blending.

### ISSUE THREAD

**Issue by lenguyenthedat** [MLWave/Kaggle-Ensemble-Guide#3]
I'm still thinking of a way to do it elegantly, maybe something like this:

```
$ cat files.csv
./samples/method1.csv,0.5
./samples/method2.csv,0.25
./samples/method2.csv,0.25

$ python kaggle_rankavg.py files.csv "./samples/kaggle_rankavg.csv"
parsing: ./samples/method1.csv with weight: 0.5
parsing: ./samples/method2.csv with weight: 0.25
parsing: ./samples/method3.csv with weight: 0.25
wrote to ./samples/kaggle_rankavg.csv
```

What do you think?

**Comment by MLWave** [comment]
I did the same, but with prefixes. If filename has prefix `_w15_` then weigh it 15 times, else weigh it 1 time. That way the file will still open as .csv. Either way it would be a nice and welcome addition.

I think using percentages like you did may be better, as it allows for more control.

**Comment by lenguyenthedat** [comment]
Can't really think of a way to implement this feature without making the whole thing more complicated (especially for the user) :disappointed: 

For now, my approach is a bit similar to yours: I just duplicate whatever the file that I want to put more weights into, for example:
- file1.csv
- file1 copy.csv
- file1 copy 2.csv
- file2.csv
- file2 copy.csv

**Comment by armaseg** [comment]
Today I needed this feature and I implemented using the filename prefix as @MLWave suggested. I'm pretty sure that there is a more elegant way to do it, nevertheless it'd be useful to some people. For instance, today using the weights I was able to improve my score by 0.00019 on Kaggle over the regular kaggle_vote.py

I'd like to know if I can create a pull request : 071c8e2cf4de3fc736d2110d9bbd72b4361b8dff

**Comment by MLWave** [comment]
> I'd like to know if I can create a pull request : 071c8e2

Please do!

**Comment by MLWave** [comment]
Pull req merged. Thanks for contributing! Ensemble Guide updated.
