### ISSUE TITLE
Submissions will need to be sorted before ensembled.

### ISSUE THREAD

**Issue by lenguyenthedat** [MLWave/Kaggle-Ensemble-Guide#5]
Often time, submissions can come from different language / libraries that might affect their orders.
I think we should have an option (or by default) to sort them beforehand to make sure we ensemble the right ids together :smiley:

**Comment by MLWave** [comment]
Yes, this bit me a few times already :). I have a script now that reorders submissions to make sure this doesn't happen, but I agree we should do this by default. I think it's possible to do without creating new files, but it would change all scripts.

I'll have a look later this week. In the meantime if you make any changes (always very welcome) I'll merge them in the repo.

Thanks for the feedback!

**Comment by lenguyenthedat** [comment]
I have a script to do that myself too! Will do it!

**Comment by MLWave** [comment]
Thank you very much!
